### PR TITLE
Update metrics.json

### PR DESCRIPTION
**Pull request by becmar**
Add new field to manage new vTU metrics

### CODE REVIEW

**Comment by becmar** [comment]
I add new vTU metrics

**Comment by jokogr** [comment]
@becmar are you exposing metrics that are generic ones (coming from collectd)? I am referring to the `disk`, `memfree` and `fsfree` ones.

If so, it is not needed, as they are automatically exposed as generic.

In any way, we might include the collectd metrics in the JSON file as well, just to inform the VNF developers which parameters they need to configure in collectd.

**Comment by becmar** [comment]
@jokogr , I know some metrics are included in collectd service but I think that describe them in metrics.json is more rigthous , as you say .

**Comment by jokogr** [comment]
Alright! As soon as those get merged, I will do another PR exposing all of
them.

**Pull request merged**
